[package]
name = "wgpu_canvas"
version = "2.1.2"
edition = "2021"
description = "wgpu renderer api for a 2d canvas, wgpu_lyon for shapes, glyhpon for text, wgpu_image for images"
license = "BSD-3-Clause"
repository = "https://github.com/CalebCouch/wgpu_canvas.git"


[dependencies]
lyon_tessellation = "1.0.15"
lyon_path = "1.0.6"
wgpu = "22.1.0"
wgpu_cyat = "1.1.0"
wgpu_image = "2.0.0"
glyphat = "1.0.1"
hex = "0.4.3"
